sched: qhmp_core: Fix build errors
The changes in commit 03420c696efa ("sched: Add commits left out during
CAF's 3.18 stable merge") should have been applied to this file as well,
otherwise there will be build errors with CONFIG_SCHED_QHMP enabled as
it replaces the entire scheduling core with the qhmp_* files.

../kernel/sched/qhmp_core.c:6269:14: error: redefinition of 'io_schedule'

Build tested with msm8937-perf_defconfig.

Closes: #6
Reported-by: Shoaib0597 <Shoaib0595@gmail.com>
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Albert I <krascgq@outlook.co.id>