fs/sdcardfs/inode.c: Fix some unused function
../fs/sdcardfs/inode.c:869:12: error: unused function 'sdcardfs_setxattr' [-Werror,-Wunused-function]
static int sdcardfs_setxattr(struct dentry *dentry, const char *name,
           ^
../fs/sdcardfs/inode.c:895:16: error: unused function 'sdcardfs_getxattr' [-Werror,-Wunused-function]
static ssize_t sdcardfs_getxattr(struct dentry *dentry, const char *name,
               ^

Signed-off-by: ronaxdevil <pratabidya.007@gmail.com>